/**
 * @profullstack/stack/crawlproof — typed, zero-dependency client for the
 * CrawlProof HTTP API (https://crawlproof.com).
 *
 * Covers the three things external apps actually do against CrawlProof:
 *
 *   1. Send trusted server-side lifecycle events (user.created, plan.changed,
 *      …) to the Audience ingest endpoint — `POST /api/events` with a
 *      per-project bearer key. This replaces the vendored
 *      `lib/crawlproof/server.ts` snippet generated by CrawlProof.
 *   2. Fire stats-tracker beacons — `POST /api/track` (the endpoint behind
 *      the drop-in /stats.js tracker). Always answered with 204.
 *   3. Poll public audit status — `GET /api/audits/<id>` — and build public
 *      share-report URLs from the returned `share_token`.
 *
 * Starting audits, listing audits, and downloading reports are NOT exposed
 * over the public REST API today (they are server actions / cookie-auth
 * pages, or MCP tools); this module intentionally does not fake them.
 *
 * Uses the global `fetch` (Node >= 18 / modern browsers); a custom fetch can
 * be injected for tests or proxies.
 */

/** Default origin every request is sent to. */
export const CRAWLPROOF_DEFAULT_BASE_URL = "https://crawlproof.com";

/** Lifecycle states of a CrawlProof audit (mirrors the `audits` table check). */
export type CrawlproofAuditStatus = "queued" | "running" | "complete" | "failed";

/**
 * A trusted server-side event for the Audience ingest endpoint
 * (`POST /api/events`). Sent with the per-project bearer key.
 */
export interface CrawlproofEvent {
  /** Event name, e.g. `"user.created"`, `"user.updated"`, `"customer.plan_changed"`. */
  event: string;
  /** Project slug the event belongs to (e.g. `"profullstack.com"`). Overrides the client's default `project`. */
  project?: string;
  /** Contact email for the user/customer the event is about. */
  email?: string;
  /** Contact display name. */
  name?: string;
  /** Your internal user id, used to stitch identities. */
  user_id?: string;
  /** Whether the user consented to marketing email. */
  marketing_consent?: boolean;
  /** Current plan name (for plan lifecycle events). */
  plan?: string;
  /** Arbitrary extra properties stored with the event. */
  metadata?: Record<string, unknown>;
}

/**
 * A stats-tracker beacon payload (`POST /api/track`). This is the same
 * contract the drop-in `/stats.js` browser tracker uses; the endpoint is
 * public, CORS-open, and always answers `204` (even for bad input).
 */
export interface CrawlproofTrackPayload {
  /** Project (site) UUID from the CrawlProof dashboard. Required. */
  site: string;
  /** Event name, e.g. `"pageview"` (default server-side), `"signup"`, … */
  event?: string;
  /** Full page URL the event happened on. */
  url?: string;
  /** Referrer URL, if any. */
  referrer?: string;
  /** Page path (used when `url` is not provided). */
  path?: string;
  /** Event target (e.g. link text / button label) for click-type events. */
  target?: string;
  /** Visitor language tag, e.g. `"en-US"`. */
  language?: string;
  /** Visitor IANA timezone, e.g. `"Europe/Berlin"`. */
  timezone?: string;
  /** Stable anonymous visitor id (first-party). */
  visitorId?: string;
  /** Session id; enables exit-page rollups for pageviews. */
  sessionId?: string;
  /** Viewport size in pixels. */
  viewport?: { width?: number; height?: number };
  /** Screen width in pixels. */
  screenWidth?: number;
  /** Screen height in pixels. */
  screenHeight?: number;
}

/**
 * The public audit record returned by `GET /api/audits/<id>`.
 * Deliberately thin — the endpoint only exposes share-safe fields.
 */
export interface CrawlproofAudit {
  /** Audit UUID. */
  id: string;
  /** Lifecycle status. */
  status: CrawlproofAuditStatus;
  /** 0–100 score once the audit is complete; `null` while running/queued. */
  score: number | null;
  /** Structured summary (engine-specific JSON blob). */
  summary: Record<string, unknown>;
  /** ISO-8601 completion timestamp; `null` until complete. */
  completed_at: string | null;
  /** Public share token for the report page; build a URL with `client.shareUrl()`. */
  share_token: string | null;
}

/**
 * Outcome of a fire-and-forget ingest call (`sendEvent`, `track`).
 * These methods never reject — delivery is best-effort by design and the
 * result is returned for callers that want to log or meter failures.
 */
export interface CrawlproofIngestResult {
  /** Whether the endpoint accepted the payload (2xx). */
  ok: boolean;
  /** HTTP status code, when a response was received. */
  status?: number;
  /** Human-readable failure reason when `ok` is false. */
  error?: string;
}

/** Options for {@link createCrawlproofClient}. */
export interface CrawlproofClientOptions {
  /**
   * Per-project bearer key for the trusted events ingest (`CRAWLPROOF_PROJECT_KEY`).
   * Without it `sendEvent` is a no-op that reports `{ ok: false }`.
   */
  apiKey?: string;
  /** API origin. Defaults to `https://crawlproof.com`. */
  baseUrl?: string;
  /** Default project slug merged into every `sendEvent` payload. */
  project?: string;
  /** Custom fetch implementation (defaults to the global `fetch`). */
  fetch?: typeof fetch;
}

/** Error thrown by read methods ({@link CrawlproofClient.getAudit}) when the API answers with an unexpected non-2xx status. */
export class CrawlproofApiError extends Error {
  /** HTTP status code returned by the API. */
  readonly status: number;

  constructor(status: number, message: string) {
    super(message);
    this.name = "CrawlproofApiError";
    this.status = status;
  }
}

/** Typed client for the CrawlProof HTTP API. Create with {@link createCrawlproofClient}. */
export interface CrawlproofClient {
  /**
   * Send a trusted lifecycle event to `POST /api/events`.
   * Best-effort: never rejects; missing `apiKey` short-circuits to
   * `{ ok: false }` without a request.
   */
  sendEvent(event: CrawlproofEvent): Promise<CrawlproofIngestResult>;
  /**
   * Send a stats-tracker beacon to `POST /api/track`.
   * Best-effort: never rejects; the endpoint always answers 204.
   */
  track(payload: CrawlproofTrackPayload): Promise<CrawlproofIngestResult>;
  /**
   * Fetch the public status of an audit via `GET /api/audits/<id>`.
   * Resolves `null` when the audit does not exist; rejects with
   * {@link CrawlproofApiError} on unexpected non-2xx responses and with the
   * underlying error on network failure.
   */
  getAudit(id: string): Promise<CrawlproofAudit | null>;
  /** Build the public share-report URL for an audit's `share_token` (`/r/<token>`). */
  shareUrl(shareToken: string): string;
}

function normalizeBaseUrl(baseUrl: string): string {
  return baseUrl.replace(/\/+$/, "");
}

/**
 * Create a typed CrawlProof API client.
 *
 * @example
 * ```ts
 * const crawlproof = createCrawlproofClient({
 *   apiKey: process.env.CRAWLPROOF_PROJECT_KEY,
 *   project: "profullstack.com",
 * });
 * await crawlproof.sendEvent({ event: "user.created", email, user_id: id });
 * const audit = await crawlproof.getAudit(auditId);
 * ```
 */
export function createCrawlproofClient(options: CrawlproofClientOptions = {}): CrawlproofClient {
  const {
    apiKey,
    baseUrl = CRAWLPROOF_DEFAULT_BASE_URL,
    project,
    fetch: fetchImpl = fetch,
  } = options;
  const origin = normalizeBaseUrl(baseUrl);

  async function post(
    path: string,
    body: unknown,
    headers: Record<string, string>,
  ): Promise<CrawlproofIngestResult> {
    try {
      const response = await fetchImpl(`${origin}${path}`, {
        method: "POST",
        headers: { "content-type": "application/json", ...headers },
        body: JSON.stringify(body),
      });
      if (!response.ok) {
        const text = await response.text().catch(() => "");
        return {
          ok: false,
          status: response.status,
          error: text || `HTTP ${response.status}`,
        };
      }
      return { ok: true, status: response.status };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  return {
    async sendEvent(event) {
      if (!apiKey) {
        return { ok: false, error: "Crawlproof apiKey is not configured" };
      }
      return post(
        "/api/events",
        { ...(project ? { project } : {}), ...event },
        { authorization: `Bearer ${apiKey}` },
      );
    },

    async track(payload) {
      return post("/api/track", payload, {});
    },

    async getAudit(id) {
      const headers: Record<string, string> = {};
      if (apiKey) headers.authorization = `Bearer ${apiKey}`;
      const response = await fetchImpl(`${origin}/api/audits/${encodeURIComponent(id)}`, {
        method: "GET",
        headers,
      });
      if (response.status === 404) return null;
      if (!response.ok) {
        throw new CrawlproofApiError(
          response.status,
          `Crawlproof GET /api/audits/${id} failed with HTTP ${response.status}`,
        );
      }
      const body = (await response.json()) as { ok?: boolean; audit?: CrawlproofAudit };
      if (!body.ok || !body.audit) return null;
      return body.audit;
    },

    shareUrl(shareToken) {
      return `${origin}/r/${encodeURIComponent(shareToken)}`;
    },
  };
}
